export type LogLevel = "debug" | "info" | "warn" | "error";

export interface LogFields {
  endpointId?: string;
  pluginId?: string;
  transport?: string;
  conversationId?: string;
  messageId?: string;
  agentId?: string;
  correlationId?: string;
  command?: string;
  backupId?: string;
  durationMs?: number;
  cacheHit?: boolean;
  errorType?: string;
  errorMessage?: string;
  errorStack?: string;
  errorCauseType?: string;
  errorCauseMessage?: string;
  agentStopReason?: string;
  upstreamErrorMessage?: string;
  upstreamProvider?: string;
  upstreamModel?: string;
  upstreamApi?: string;
  upstreamResponseId?: string;
  assistantContentTypes?: string[];
  assistantTextLength?: number;
  assistantToolCallNames?: string[];
  assistantHasThinking?: boolean;
  fileName?: string;
  failedPath?: string;
  errorRecordPath?: string;
  rootDir?: string;
  inboxDir?: string;
  processingDir?: string;
  processedDir?: string;
  failedDir?: string;
  outboxDir?: string;
  hookName?: string;
  hookRegistrationName?: string;
  skillCount?: number;
  skillNames?: string[];
  configuredSkillCount?: number;
  configuredSkillNames?: string[];
  configuredInstructionFileCount?: number;
  configuredInstructionFiles?: string[];
  configuredReferenceFileCount?: number;
  configuredReferenceFiles?: string[];
  basePromptSource?: "built-in" | "file" | "text" | "unknown";
  basePromptFile?: string;
  basePromptBuiltIn?: string;
  instructionFileCount?: number;
  instructionFiles?: string[];
  agentHomeInstructionFileCount?: number;
  agentHomeInstructionFiles?: string[];
  workspaceInstructionFile?: string;
  referenceFileCount?: number;
  referenceFiles?: string[];
  globalSkillsPath?: string;
  agentHomeSkillsPath?: string;
  workspaceDirectory?: string;
  workspaceSkillsPath?: string;
  overriddenSkillNames?: string[];
  initialWorkingDirectory?: string;
  configuredBuiltInTools?: string[];
  resolvedBuiltInTools?: string[];
  interruptedRunCount?: number;
  missingBuiltInTools?: string[];
  configuredMcpServers?: string[];
  initializedMcpServers?: string[];
  failedMcpServers?: string[];
  resolvedMcpTools?: string[];
  resolvedTools?: string[];
}

export interface Logger {
  debug(message: string, fields?: LogFields): Promise<void>;
  info(message: string, fields?: LogFields): Promise<void>;
  error(message: string, fields?: LogFields, error?: unknown): Promise<void>;
}
